workflows:
    sample-workflow:
        name: Codemagic Sample Workflow
        instance_type: mac_mini_m2
        scripts:
            - name: Get dependencies
              script: flutter packages pub get
            - name: Build Fat APK
              script: flutter build apk --release --fat-apk
        artifacts:
            - build/app/outputs/flutter-apk/*.apk
